Fix bugs with `~/.files/tinify`
The file(1) command's `--mime` switch was including the encoding-type in
its output, which I don't recall seeing when I first wrote this utility.
Using `--mime-type` would be shorter, but the approach used here is more
foolproof (a file(1) implementation might not support `--mime-type`, for
example).

diff --git a/bin/tinify b/bin/tinify
--- a/bin/tinify
+++ b/bin/tinify
@@ -4,10 +4,10 @@
 # tinify: Compress images with TinyPNG
 #
 usage='tinify [-h|--help] [-v|--version] ...images'
-version='v1.0.0'
+version='v1.1.0'
 
 # Parse command-line switches
-while [ -n "$1" ]; do case $1 in
+while [ $# -gt 0 ]; do case $1 in
 
 	# Print a usage summary and exit
 	-h|--help|-\?)
@@ -47,8 +47,8 @@ done
 
 # Check dependencies are available
 for i in curl file; do
-	command -v $i 2>&1 >/dev/null || {
-		>&2 printf 'tinify: Required utility `%s` not found in $PATH\n' $i
+	command -v $i >/dev/null 2>&1 || {
+		>&2 printf 'tinify: Required utility `%s` not found in $PATH\n' "$i"
 		exit 1
 	};
 done
@@ -56,7 +56,7 @@ done
 
 # Locate API key
 key=${TINIFY_KEY:-${TINIFY_API_KEY}}
-[ ! "$key" ] && [ -s ~/.tinify ] && key=`head -1 ~/.tinify`
+[ ! "$key" ] && [ -s ~/.tinify ] && read -r key < ~/.tinify
 [ ! "$key" ] && {
 	>&2 printf 'tinify: Unable to locate API key\n';
 	exit 2;
@@ -65,18 +65,21 @@ key=${TINIFY_KEY:-${TINIFY_API_KEY}}
 # Handle arguments list
 for file in "$@"; do
 
+	# Ignore anything that isn't an ordinary file
+	[ -f "$file" ] || continue
+
 	# Skip unsupported filetypes
-	case `file --brief --mime "$file"` in
+	type=`file --brief --mime "$file"`
+	case ${type%%;*} in
 		image/png | image/jpeg) ;;
 		*) continue ;;
 	esac
 
 	>&2 printf 'Compressing: %s\n' "$file"
 	curl 'https://api.tinify.com/shrink' \
-		--user "api:$key" -qs \
-		--data-binary @"$file" \
-		--dump-header /dev/stdout \
-	| sed -n 's/^location:[[:blank:]]*\(.*\)$/\1/p' \
+		--user "api:$key" -qsi \
+		--data-binary "@$file" \
+	| sed -n 's/^[Ll]ocation:[[:blank:]]*\(.*\)$/\1/p' \
 	| tr -d '\r\n' \
 	| xargs -J% curl -qso "$file" "%";
 done
